# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Compute the inverse of a matrix
#'
#'@param A a matrix
#'
#'
invC <- function(A) {
    .Call(`_mypkgr_invC`, A)
}

#'Based on the implementation from Nino Hardt and Dicko Ahmadou
#'http://gallery.rcpp.org/articles/dmvnorm_arma/
#'(accessed in August 2014)
#'
#'@rdname mvnpdf
#'@export
#'
mvnpdfC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_mypkgr_mvnpdfC`, x, mean, varcovM, Log)
}

#'@rdname mvnpdf
#'@export
timesTwo <- function(x) {
    .Call(`_mypkgr_timesTwo`, x)
}

